from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source" / "atlas.json"


def apply_chapter(lesson: dict, chapter: dict) -> None:
    lesson.update({
        "description": chapter["description"],
        "prerequisites": chapter["prerequisites"],
        "learningObjectives": chapter["objectives"],
        "interviewAnswer": chapter["answer"],
        "keyPoints": chapter["keys"],
        "why": chapter["why"],
        "intuition": chapter["intuition"],
        "deepDive": "The full explanation is organized into the structured sections below.",
        "deepSections": chapter["sections"],
        "math": chapter["formal"],
        "workedExample": chapter["example"]["walkthrough"],
        "workedExamples": [chapter["example"]],
        "commonMistakes": chapter["mistakes"],
        "followUps": chapter["followups"],
        "production": chapter["production"],
        "exercises": chapter["exercises"],
        "resources": chapter["resources"],
        "sourceNotes": chapter["notes"],
        "visuals": chapter["visuals"],
        "lab": chapter["lab"],
        "editorial": {"status": "verified", "verifiedOn": "2026-08-21"},
    })
    lesson.pop("visual", None)


def apply() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    data["resources"].update({
        "numpy-linalg": {
            "title": "NumPy Linear Algebra Reference",
            "provider": "NumPy",
            "kind": "Official documentation",
            "level": "Intermediate",
            "url": "https://numpy.org/doc/stable/reference/routines.linalg.html",
            "why": "Current official APIs for products, norms, decompositions, eigenproblems, condition numbers, solves, least squares and pseudoinverses.",
        },
        "goldberg-floating": {
            "title": "What Every Computer Scientist Should Know About Floating-Point Arithmetic",
            "provider": "David Goldberg / Oracle",
            "kind": "Foundational paper",
            "level": "Advanced",
            "url": "https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html",
            "why": "Canonical explanation of rounding, representation, cancellation, error and IEEE floating-point behavior.",
        },
        "scipy-logsumexp": {
            "title": "scipy.special.logsumexp",
            "provider": "SciPy",
            "kind": "Official documentation",
            "level": "Intermediate",
            "url": "https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logsumexp.html",
            "why": "Official stable implementation and behavior for log-domain summation without avoidable overflow or underflow.",
        },
    })
    lessons = {lesson["slug"]: lesson for lesson in data["lessons"]}

    apply_chapter(lessons["vectors-matrices"], {
        "description": "Vectors and matrices are representations of linear relationships, not just rectangular containers of numbers. A vector can encode coordinates, features, parameters, probabilities or a direction; a matrix can encode a linear map, a collection of observations, a graph or a change of basis. This chapter builds the subject from shape and orientation through vector addition, scaling, inner and outer products, matrix-vector and matrix-matrix multiplication, transpose, identity, inverse, rank, column space, null space and affine bias. You will learn to read every multiplication as both a shape contract and a composition of transformations, distinguish elementwise multiplication from contraction, and explain why solving a linear system is preferable to explicitly forming an inverse. A worked batch prediction traces indices and dimensions from features to outputs. The implementation material exposes multiplication with loops, then uses NumPy while checking shapes and invariants. Production guidance covers dtype, broadcasting, memory layout, batching, sparse structure, conditioning, thread oversubscription, serialization and privacy. The goal is to make shape reasoning and geometric meaning automatic enough that later topics—least squares, gradients, attention, embeddings and neural networks—feel like precise extensions rather than new notation to memorize.",
        "prerequisites": [],
        "objectives": [
            "Interpret vectors and matrices simultaneously as arrays, coordinate representations, collections of examples and linear transformations.",
            "Derive shapes and index formulas for dot, outer, matrix-vector and matrix-matrix products and reject invalid broadcasting.",
            "Use rank, column space and null space to reason about solvability, identifiability and information loss in real systems.",
        ],
        "answer": "A vector is an ordered coordinate representation; a matrix often represents a linear map or a batch of vectors. If A has shape m×n and x has shape n, then Ax has shape m and each output is a row of A dotted with x. If B is n×p, AB is m×p and composes B followed by A. The dot product measures aligned magnitude and defines geometry; the outer product creates a rank-one matrix. Rank counts independent directions preserved by a map, the column space contains possible outputs, and the null space contains inputs mapped to zero. Track orientation and shapes explicitly, distinguish `@` from elementwise `*`, and solve systems rather than computing inverses explicitly.",
        "keys": ["Shape is part of meaning", "Matrix multiplication composes maps", "Dot and outer products differ", "Rank counts independent directions", "Solve systems; avoid explicit inverse"],
        "why": "Most ML bugs involving linear algebra are not advanced-theorem failures. They are silent transposes, unintended broadcasting, inconsistent batch conventions, dtype overflow, or a model trying to estimate directions the data does not identify. Linear algebra supplies a compact language for feature transformations, regression, embeddings, convolutions, attention and optimization. Understanding what a product means lets you validate tensor code, choose stable algorithms and explain when data has lost information.",
        "intuition": "A matrix is a machine whose columns show where basis directions go. Feeding vector x forms a weighted sum of those columns, with weights from x. Matrix multiplication connects machines: B transforms the input, then A transforms B's output. A dataset matrix uses a different but compatible story—rows are examples and columns are features—so multiplying by a parameter vector takes one dot product per example. Always state which convention you use.",
        "sections": [
            {"id": "objects-shapes", "title": "Vectors, matrices, orientation, and shape", "body": "A vector in R^n is an ordered n-tuple once a basis is chosen. Geometrically it can represent a displacement; in data work it may represent one example's features, one embedding, or model parameters. A matrix A∈R^{m×n} has m rows and n columns. Its meaning comes from the domain, codomain and chosen bases, not only values. A column-vector convention treats A as a map R^n→R^m. A tabular dataset often stores N examples as rows X∈R^{N×d}; then predictions Xw use the same rule with one output per row.\n\nAddition requires equal shape and combines corresponding coordinates. Scalar multiplication stretches or reverses a vector. Transpose exchanges axes: if A is m×n, A^T is n×m. For real vectors, a row x^T and column y can form the scalar x^T y, while xy^T is an outer product matrix. In code, a one-dimensional array may have shape `(n,)` rather than explicit `(n,1)`, so transpose can appear to do nothing. Add axes deliberately when orientation matters.\n\nShapes function like types. Before computing, label every axis: batch, feature, output, time, head or class. A valid numerical shape can still be semantically wrong—for example, broadcasting a per-class bias across the feature axis when dimensions happen to match. Name axes in comments/tests and include small asymmetric cases that expose swaps."},
            {"id": "products-transformations", "title": "Products as contractions and transformations", "body": "The inner or dot product x^T y=Σ_i x_i y_i returns a scalar. It is bilinear and, in Euclidean coordinates, connects algebra to length and angle. An outer product xy^T has entries x_i y_j and rank at most one. Elementwise or Hadamard multiplication x⊙y preserves shape. These operations answer different questions; overloaded library functions and broadcasting make the distinction important.\n\nFor A∈R^{m×n} and x∈R^n, y=Ax has y_i=Σ_j A_{ij}x_j. Each output is a row-vector dot product, and simultaneously y is a linear combination of A's columns. For A∈R^{m×n} and B∈R^{n×p}, C=AB has C_{ik}=Σ_j A_{ij}B_{jk}. The shared dimension n is contracted and the outer dimensions m,p remain. Composition order matters: AB means apply B first, then A under column-vector convention; generally AB≠BA.\n\nAssociativity permits `(AB)x=A(Bx)`, but computational cost and intermediate memory differ. If x is a vector, applying B then A can be much cheaper than forming AB. Distributivity supports batching and decomposition. Matrix multiplication is not elementwise and cannot be justified by “matching total element counts.” Write index notation for one output when a tensor contraction is unclear."},
            {"id": "subspaces-rank", "title": "Column space, null space, rank, and solvability", "body": "The column space of A is the set of all Ax: every output reachable by combining columns. The null space is the set of x with Ax=0: input directions erased by the transformation. Rank is the dimension of the column space and equals the number of independent rows. By rank-nullity for A:R^n→R^m, rank(A)+nullity(A)=n. A rank-deficient design matrix contains redundant or unobserved feature directions, so different parameter vectors can produce the same predictions.\n\nThe system Ax=b has an exact solution only when b lies in the column space. If columns are independent and m≥n, a solution is unique when it exists. If the null space is nontrivial, adding any null vector to a solution produces another. Overdetermined inconsistent systems lead to least squares; underdetermined systems need a criterion such as minimum norm or regularization. Rank in floating point is threshold-dependent because tiny singular values may represent noise rather than meaningful directions.\n\nThe identity I leaves vectors unchanged. An inverse A^{-1} exists only for a square full-rank matrix and reverses the map. In numerical work, compute `solve(A,b)` rather than `inv(A)@b`: factorization-based solves are typically more stable and efficient. Rectangular or singular problems use least squares or pseudoinverse concepts, with conditioning and regularization considered separately."},
            {"id": "implementation-operation", "title": "Implementation, batching, and production checks", "body": "Dense multiplication cost for m×n times n×p is roughly proportional to mnp scalar multiply-adds, but optimized BLAS libraries use cache blocking, vector instructions, multiple cores and accelerators. Memory layout and contiguous access affect throughput. Sparse matrices store only nonzeros and can reduce work dramatically when sparsity patterns and operations are supported; converting to dense may destroy that benefit. Batch dimensions let libraries execute many products efficiently, but broadcasting rules must match intended semantics.\n\nDtype affects range, precision, memory and hardware. Integer multiplication can overflow; low-precision floating point may need higher-precision accumulation or loss scaling. Validate finiteness, shapes, units and expected norm/range before and after critical transforms. Compare a small case with a trusted implementation, test identity and associativity within tolerance, and use relative as well as absolute tolerance. Exact equality is inappropriate after most floating-point operations.\n\nIn production, record feature order and preprocessing with the model; a mathematically valid matrix applied to reordered columns is wrong. Bound input sizes to prevent memory denial of service, control BLAS/thread pools to avoid oversubscription, batch under latency limits, and monitor NaN/Inf, shape failures and output drift. Quantization, sparse kernels and accelerator changes require accuracy regression. Embeddings and matrices can contain sensitive information, so apply access control and retention policy to artifacts and logs."},
        ],
        "formal": "For A∈R^{m×n}, B∈R^{n×p}, (AB)_{ik}=Σ_{j=1}^n A_{ij}B_{jk}. For x∈R^n, Ax=Σ_j x_j a_j where a_j are A's columns. The fundamental subspaces include Col(A)⊆R^m and Null(A)⊆R^n, with rank(A)+dim Null(A)=n. A linear map satisfies T(αx+βy)=αT(x)+βT(y); an affine map Ax+b adds a translation and is not linear unless b=0.",
        "example": {"title": "Batch linear prediction with explicit axes", "setup": "Three examples have four features and a model produces two outputs plus a bias.", "walkthrough": "Let X have shape 3×4, with rows as examples. Let W have shape 4×2, whose columns parameterize the two outputs, and b have shape 2. Then Z=XW+b has shape 3×2. In indices, Z_{ik}=Σ_{j=1}^4 X_{ij}W_{jk}+b_k. The feature dimension is contracted; batch and output dimensions remain. Broadcasting b across rows is intended because b_k is output-specific. Tests use 3,4,2 rather than equal dimensions so an accidental transpose fails. Verify `Z[i,k]` by a manual dot product, check zero X produces repeated b, and store the feature-name order with W. If X has dependent columns, multiple W values may yield the same predictions even though the product is defined.", "conclusion": "Shape derivation tells both the code operation and the semantic axes that must be preserved."},
        "mistakes": [
            {"mistake": "If NumPy broadcasts, the operation must be mathematically intended.", "correction": "Broadcast compatibility checks sizes, not semantic axes; label axes and test asymmetric shapes."},
            {"mistake": "Matrix multiplication is elementwise multiplication.", "correction": "Matrix multiplication contracts an inner dimension and composes transformations; elementwise multiplication preserves shape."},
            {"mistake": "Compute an inverse whenever solving Ax=b.", "correction": "Use a factorization-based solve; inverses are usually slower, less stable and unavailable for rectangular/rank-deficient systems."},
        ],
        "followups": [
            {"question": "What does matrix rank mean?", "answer": "The number of independent output directions, equivalently the dimension of the column space and row space."},
            {"question": "Why is matrix multiplication not commutative?", "answer": "It composes maps in order; changing order changes the intermediate space and transformation and may not even be shape-valid."},
            {"question": "What is the difference between linear and affine?", "answer": "A linear map is Ax and preserves zero and linear combinations; an affine map Ax+b adds a translation and maps zero to b."},
        ],
        "production": "Persist axis meaning, feature order, dtype and preprocessing with every artifact. Validate shapes, finiteness, ranges, rank/conditioning when relevant and small trusted cases. Use optimized solve/decomposition routines, control threads and batch sizes, preserve sparsity, and test low-precision or accelerator changes against accuracy tolerances. Monitor shape errors, NaN/Inf, latency, memory and output drift; restrict access to sensitive feature and embedding matrices.",
        "exercises": [
            {"difficulty": "recall", "prompt": "If A is 5×3 and B is 3×7, what is the shape of AB and which dimension is contracted?", "solution": "AB is 5×7; the shared dimension of size 3 is summed over."},
            {"difficulty": "application", "prompt": "Interpret Xw when X is N×d and w is d.", "solution": "It produces N scalar predictions, one dot product between each example row and the feature-parameter vector."},
            {"difficulty": "diagnosis", "prompt": "Two different parameter vectors make identical predictions for every training row. What linear-algebra property explains this?", "solution": "Their difference lies in the null space of the design matrix; the matrix is rank-deficient in that parameter direction."},
        ],
        "resources": ["mit-linear-algebra", "3b1b-linear-algebra", "numpy-linalg"],
        "notes": [
            {"resource": "mit-linear-algebra", "contribution": "Provides rigorous coverage of Ax=b, subspaces, rank, transformations, multiplication and inverse/solve concepts."},
            {"resource": "3b1b-linear-algebra", "contribution": "Supplies geometric intuition for vectors, bases, linear maps, products and subspaces."},
            {"resource": "numpy-linalg", "contribution": "Documents current array products and production linear-algebra routines backed by BLAS/LAPACK."},
        ],
        "visuals": [
            {"type": "flow", "title": "Matrix product as axis contraction", "items": ["X: batch × feature", "W: feature × output", "Contract shared feature axis", "Z: batch × output", "Broadcast output bias"], "caption": "The shared axis is summed; the surviving axes define the result and its semantic meaning.", "afterSection": "products-transformations"},
            {"type": "compare", "title": "Four products, four meanings", "left": {"title": "Scalar or same-shape", "items": ["Dot: aligned magnitude → scalar", "Hadamard: coordinatewise → same shape"]}, "right": {"title": "New transformation", "items": ["Outer: pair every coordinate → matrix", "Matrix product: compose maps → contracted shape"]}, "caption": "Similar notation can hide different shape and geometric contracts.", "afterSection": "objects-shapes"},
        ],
        "lab": {
            "goal": "Implement matrix multiplication from its index definition, then verify shape, manual entries, identity, associativity and NumPy agreement.",
            "language": "python",
            "buildIt": "def matmul(a,b):\n    if not a or not b or len(a[0])!=len(b): raise ValueError('shape mismatch')\n    if any(len(row)!=len(a[0]) for row in a) or any(len(row)!=len(b[0]) for row in b): raise ValueError('ragged')\n    return [[sum(a[i][k]*b[k][j] for k in range(len(b))) for j in range(len(b[0]))] for i in range(len(a))]\n\ndef transpose(a):\n    return [list(col) for col in zip(*a)]",
            "useIt": "import numpy as np\nA=[[1.,2.,3.],[4.,5.,6.]]\nB=[[2.,0.],[1.,1.],[0.,3.]]\nmanual=matmul(A,B)\nnp_result=np.asarray(A)@np.asarray(B)\nI=np.eye(2)\nC=np.array([[1.,2.],[0.,1.]])",
            "verifyIt": "assert manual==[[4.0,11.0],[13.0,23.0]]\nassert np.allclose(manual,np_result)\nassert np_result.shape==(2,2)\nassert np_result[1,0]==sum(A[1][k]*B[k][0] for k in range(3))\nassert np.allclose(I@np_result,np_result)\nassert np.allclose((np_result@C)@I,np_result@(C@I))\ntry: matmul([[1,2]],[[1,2]])\nexcept ValueError: pass\nelse: raise AssertionError('invalid contraction must fail')",
            "shipIt": "Use named axis contracts, trusted BLAS/LAPACK routines, dtype and finiteness checks, thread/batch limits, versioned feature order and numerical regression before deploying matrix-heavy paths.",
        },
    })

    apply_chapter(lessons["norms-distances"], {
        "description": "Norms measure vector or matrix magnitude; metrics measure distance between objects; similarity functions rank resemblance but may not satisfy metric axioms. Those choices encode geometry and can change nearest neighbors, clustering, regularization, robustness and retrieval quality. This chapter develops L1, L2, L∞ and general Lp norms, weighted and Mahalanobis distance, cosine similarity, Hamming distance and key matrix norms. You will learn the norm and metric axioms, the role of scaling and covariance, why cosine discards magnitude, how high-dimensional distance concentration changes intuition, and why comparing raw mixed-unit features is usually meaningless. A worked retrieval example contrasts Euclidean and cosine rankings before and after normalization. The lab implements core measures, checks symmetry, triangle inequality examples and library agreement, and rejects zero-vector cosine. Production guidance covers preprocessing/versioning, approximate nearest-neighbor index compatibility, floating-point clipping, missing values, privacy, distribution drift and monitoring of neighbor stability. The goal is to make “distance” a modeled assumption tied to invariances and decision cost, not a default call chosen after features have already defined an accidental geometry.",
        "prerequisites": ["vectors-matrices"],
        "objectives": [
            "Distinguish norms, metrics and similarities and verify the properties each downstream algorithm assumes.",
            "Choose Lp, cosine, weighted or Mahalanobis geometry from feature units, invariances, covariance and task cost.",
            "Operate distance-based systems with stable preprocessing, index-metric consistency, drift checks and meaningful retrieval evaluation.",
        ],
        "answer": "A norm measures magnitude and must be nonnegative, definite, homogeneous and satisfy the triangle inequality. A metric measures pairwise distance and must be nonnegative, identity-preserving, symmetric and satisfy the triangle inequality. L1 sums absolute coordinates, L2 is Euclidean length, and L∞ takes the largest absolute coordinate. Cosine similarity uses angle and ignores positive scale after normalization; cosine distance conventions are not always metrics. Feature scaling defines the geometry, while Mahalanobis distance accounts for covariance through a positive semidefinite precision matrix. Choose the measure from desired invariances and costs, then keep preprocessing and ANN index configuration consistent.",
        "keys": ["Geometry is a modeling choice", "Scaling changes nearest neighbors", "Cosine ignores positive magnitude", "Mahalanobis uses covariance structure", "Index and evaluation metric must agree"],
        "why": "K-nearest neighbors, clustering, anomaly detection, recommenders and embedding search are only as meaningful as their geometry. Age measured in years and income in cents make unscaled Euclidean distance mostly income. Cosine can call a tiny and huge vector identical in direction even when magnitude carries confidence or activity. Correlated features can be counted twice. A mathematically valid metric may also misalign with false-positive and false-negative costs. Production retrieval requires the metric, preprocessing, index and evaluation to be one versioned system.",
        "intuition": "A norm draws a unit ball around the origin. L2 draws a circle, L1 a diamond and L∞ a square in two dimensions. Those shapes decide which deviations cost equally and which points are near. Scaling an axis stretches the map before measuring. Cosine looks only at direction from the origin, while Mahalanobis first reshapes correlated, differently scaled data into a standardized space.",
        "sections": [
            {"id": "axioms-lp", "title": "Norm and metric foundations", "body": "A norm ||x|| on a vector space is nonnegative, equals zero only at zero, is absolutely homogeneous `||αx||=|α| ||x||`, and obeys `||x+y||≤||x||+||y||`. It induces a metric d(x,y)=||x−y||. A metric instead starts with pairwise axioms: nonnegativity, identity of indiscernibles, symmetry and triangle inequality. A similarity may be larger for closer items but need satisfy none of these; algorithms relying on triangle-inequality pruning can fail or lose guarantees with a nonmetric score.\n\nFor p≥1, `||x||_p=(Σ|x_i|^p)^{1/p}`. L1 tolerates a few large coordinate differences differently and produces diamond-shaped balls; L2 is rotation-invariant Euclidean length; L∞ is the maximum absolute difference and enforces a worst-coordinate view. The expression with p<1 encourages sparsity-like behavior but is not a norm because the triangle inequality fails. L0 is informal notation for nonzero count, not a norm.\n\nWeighted norms encode coordinate importance and units. Positive weights in weighted Euclidean distance correspond to scaling axes. Weights should derive from measurement scale or task cost, not be tuned against a leaked test set. Standardization by training statistics can prevent a large-unit feature from dominating, but it does not make every feature semantically comparable."},
            {"id": "cosine-covariance", "title": "Angle, correlation, and covariance-aware distance", "body": "Cosine similarity is `(x·y)/(||x||_2||y||_2)` for nonzero vectors. It measures angle and is invariant to positive rescaling. If vectors are L2-normalized, squared Euclidean distance and cosine similarity are monotonically related: `||x−y||²=2−2cos(x,y)`. This equivalence explains why an index for normalized inner product can serve cosine ranking, but only when normalization is actually applied. Define behavior for zero vectors rather than returning an unexplained NaN. Floating error can push a computed cosine slightly outside [-1,1], so clip before inverse cosine.\n\nCentered cosine becomes correlation-like and removes coordinate means, which changes the object being compared. Dot product preserves both norm and alignment and may favor high-magnitude items. Decide whether magnitude represents popularity, confidence, exposure or an unwanted nuisance. Retrieval evaluation should reveal this rather than relying on intuition alone.\n\nMahalanobis distance is `sqrt((x−y)^T Σ^{-1}(x−y))`, where Σ is a covariance estimate or another positive semidefinite scale matrix. It downweights high-variance directions and accounts for correlations; equivalently, it is Euclidean distance after whitening. Singular or poorly estimated covariance requires regularization, diagonal approximation, shrinkage or a learned low-rank transform. Estimate it on training data only and monitor drift."},
            {"id": "high-dimensional", "title": "High-dimensional geometry and alternative domains", "body": "As dimension grows, points can become sparse relative to volume and distances may concentrate: nearest and farthest distances become less separated under some distributions. Irrelevant noisy dimensions accumulate in L2, while a handful of extreme coordinates can dominate L∞. This does not mean all high-dimensional distance is useless; learned embeddings exploit low-dimensional structure, normalization and task supervision. It means raw dimensionality and distribution must be measured.\n\nInspect neighbor-distance ratios, recall, hubness (a few points appearing in many neighbor lists), cluster stability and performance across slices. Dimensionality reduction or feature selection can improve signal but may erase minority structure. Approximate nearest-neighbor algorithms trade exact recall for speed and support different metrics. Index build metric, query preprocessing and reranking metric must match or be explicitly staged.\n\nOther domains need other distances. Hamming counts unequal positions for fixed-length categorical/binary strings. Jaccard compares set intersection to union. Edit distance models insertions, deletions and substitutions. Dynamic time warping aligns sequences at nonlinear time but can match implausible paths without constraints. Geodesic distance is needed on the sphere; treating latitude/longitude as planar coordinates causes distortion. Choose a domain-valid representation before choosing an efficient index."},
            {"id": "production-geometry", "title": "Evaluation and production geometry", "body": "Version the full transform: field selection, missing-value policy, categorical encoding, centering/scaling, embedding model, normalization and metric. Fit learned statistics only on training/reference data. The same raw item processed by two versions may land in incompatible coordinate systems, so rebuild or dual-index migrations. Validate finite values and dimension; reject or explicitly route zero vectors; enforce bounded query sizes.\n\nOffline evaluation uses labeled relevance, recall@k, precision@k, ranking metrics and task-specific costs, plus ANN recall against an exact subset. Compare simple baselines and inspect qualitative neighbors. Segment by language, geography, item popularity and sensitive cohorts because one global metric can hide failures. Online metrics must separate retrieval quality from later ranking and user feedback loops.\n\nMonitor embedding/norm distributions, zero and missing rates, nearest-distance distribution, hubness, index freshness, ANN recall samples, latency and memory. Drift may require recalibration or re-embedding. Do not log raw sensitive vectors casually; embeddings can leak membership or attributes. Apply access control, deletion and retention across indices and backups. Have rollback to a prior compatible embedding-index-metric bundle, not only old application code."},
        ],
        "formal": "For p≥1, ||x||_p=(Σ_i|x_i|^p)^{1/p}. A norm-induced distance d_p(x,y)=||x−y||_p is a metric. Cosine similarity is s(x,y)=x^Ty/(||x||_2||y||_2) for nonzero x,y. Mahalanobis squared distance is d_M²=(x−y)^TM(x−y), where M is positive semidefinite; if M=L^TL, this equals ||L(x−y)||_2².",
        "example": {"title": "Magnitude versus direction in retrieval", "setup": "A query q=(1,1) compares document A=(10,10) and B=(1,0).", "walkthrough": "Cosine gives A similarity 1 because it points in exactly q's direction, while B has similarity 1/√2. Raw Euclidean distance makes B much closer: `||q−B||=1`, whereas `||q−A||=√162`. Neither result is a contradiction. If vector magnitude reflects document length and should be ignored, L2-normalize query and documents and use cosine or equivalent Euclidean distance on normalized vectors. If magnitude represents calibrated confidence or activity that should matter, discarding it is wrong. Evaluate relevance labels and inspect norm correlations. Store the chosen normalization with the index and reject zero vectors.", "conclusion": "The two measures answer different invariance questions; task evidence decides which geometry is useful."},
        "mistakes": [
            {"mistake": "Standardize features using the entire dataset before evaluation.", "correction": "That leaks validation/test distribution; fit transform statistics on training data and version them."},
            {"mistake": "Cosine similarity and dot product are always interchangeable.", "correction": "Only after consistent normalization; raw dot product also depends on vector norms."},
            {"mistake": "Any distance-like score is a metric.", "correction": "Check identity, symmetry and triangle inequality before relying on metric-index guarantees."},
        ],
        "followups": [
            {"question": "When are cosine and Euclidean rankings equivalent?", "answer": "For L2-normalized vectors, squared Euclidean distance is `2−2cosine`, so one decreases exactly as the other increases."},
            {"question": "What problem does Mahalanobis distance address?", "answer": "Different scales and correlated directions; it measures Euclidean distance after a covariance-aware linear transformation."},
            {"question": "Why can distance degrade in high dimensions?", "answer": "Noise accumulates, volume is sparse and nearest/farthest distances may concentrate; learned structure and evaluation are needed."},
        ],
        "production": "Version features, learned scaling, embedding model, normalization, metric and ANN configuration as one artifact. Validate dimension, finiteness, missing/zero behavior and index compatibility; evaluate exact and approximate retrieval on representative labels and slices. Monitor norms, neighbor distances, hubness, recall, freshness, latency and drift. Protect and delete sensitive vectors across indexes/backups, bound requests and keep a prior compatible bundle for rollback.",
        "exercises": [
            {"difficulty": "recall", "prompt": "State the four norm properties.", "solution": "Nonnegativity, definiteness, absolute homogeneity and the triangle inequality."},
            {"difficulty": "application", "prompt": "When should cosine be preferred to raw dot product?", "solution": "When direction/pattern matters and positive magnitude is a nuisance; normalize consistently and verify with retrieval metrics."},
            {"difficulty": "diagnosis", "prompt": "Income dominates a customer nearest-neighbor model. What is likely wrong?", "solution": "Feature units define an unintended geometry. Fit appropriate scaling/weighting on training data and reconsider semantic comparability."},
        ],
        "resources": ["mit-linear-algebra", "3b1b-linear-algebra", "numpy-linalg"],
        "notes": [
            {"resource": "mit-linear-algebra", "contribution": "Grounds inner products, orthogonality, norms, positive-definite geometry and linear transformations."},
            {"resource": "3b1b-linear-algebra", "contribution": "Provides visual intuition for length, angle, basis change and transformed geometry."},
            {"resource": "numpy-linalg", "contribution": "Documents current norm and linear-algebra implementations used in the verified lab and production code."},
        ],
        "visuals": [
            {"type": "compare", "title": "Unit-ball geometry changes what counts as near", "left": {"title": "Coordinate-focused", "items": ["L1: total absolute deviation", "L∞: worst coordinate deviation", "Axis scaling changes shape"]}, "right": {"title": "Direction / covariance", "items": ["L2: Euclidean rotation-invariant", "Cosine: direction, not magnitude", "Mahalanobis: whitened geometry"]}, "caption": "Each choice encodes invariances and costs; no geometry is universally neutral.", "afterSection": "axioms-lp"},
            {"type": "flow", "title": "Production retrieval geometry", "items": ["Select domain-valid features", "Fit scale / embedding", "Normalize if required", "Build index with matching metric", "Retrieve + rerank", "Evaluate labels and slices", "Monitor drift + recall"], "caption": "The metric cannot be separated from preprocessing, index capabilities and evaluation.", "afterSection": "production-geometry"},
        ],
        "lab": {
            "goal": "Implement L1, L2, L∞ and cosine, then verify metric properties, normalized equivalence and NumPy agreement.",
            "language": "python",
            "buildIt": "import math\n\ndef lp(x,y,p):\n    if len(x)!=len(y): raise ValueError('shape mismatch')\n    delta=[abs(a-b) for a,b in zip(x,y)]\n    if p==math.inf: return max(delta,default=0.0)\n    if p<1: raise ValueError('p must be at least 1')\n    return sum(value**p for value in delta)**(1/p)\n\ndef cosine(x,y):\n    dot=sum(a*b for a,b in zip(x,y)); nx=math.sqrt(sum(a*a for a in x)); ny=math.sqrt(sum(b*b for b in y))\n    if nx==0 or ny==0: raise ValueError('zero vector')\n    return max(-1.0,min(1.0,dot/(nx*ny)))",
            "useIt": "import numpy as np\nx=np.array([1.,2.,-1.]); y=np.array([3.,0.,2.]); z=np.array([0.,1.,1.])\nmanual={'l1':lp(x,y,1),'l2':lp(x,y,2),'linf':lp(x,y,math.inf),'cosine':cosine(x,y)}\nlibrary={'l1':np.linalg.norm(x-y,1),'l2':np.linalg.norm(x-y,2),'linf':np.linalg.norm(x-y,np.inf),'cosine':float(x@y/(np.linalg.norm(x)*np.linalg.norm(y)))}",
            "verifyIt": "assert all(math.isclose(manual[k],library[k]) for k in manual)\nassert math.isclose(lp(x,y,2),lp(y,x,2))\nassert lp(x,z,2)<=lp(x,y,2)+lp(y,z,2)+1e-12\nxn=x/np.linalg.norm(x); yn=y/np.linalg.norm(y)\nassert math.isclose(np.linalg.norm(xn-yn)**2,2-2*cosine(xn,yn),rel_tol=1e-12)\ntry: cosine([0.,0.],[1.,0.])\nexcept ValueError: pass\nelse: raise AssertionError('zero cosine must be defined explicitly')",
            "shipIt": "Version preprocessing, normalization, metric and index together; validate zero/missing vectors, benchmark ANN recall against exact search, monitor norm/neighbor drift and retain a compatible rollback index.",
        },
    })

    apply_chapter(lessons["projections-least-squares"], {
        "description": "Orthogonal projection chooses the point in a subspace closest to a target, and least squares uses that geometry to fit inconsistent linear systems. Given a design matrix A and observations b, the fitted vector A x̂ is the projection of b onto A's column space, so the residual is orthogonal to every column. This chapter derives normal equations, explains why QR and singular value decomposition are safer computational routes, and connects rank, pseudoinverse, minimum-norm solutions, regularization, leverage and residual diagnostics. You will learn to construct projection onto a vector or orthonormal basis, distinguish coefficient uncertainty from predictive error, include intercepts and categorical encodings correctly, and identify when collinearity or ill-conditioning makes coefficients unstable even though predictions look reasonable. A worked line fit checks residual orthogonality by hand and with NumPy. Production guidance covers train/test separation, scaling, solver choice, dtype, robust alternatives, monitoring, privacy, artifact versioning and rollback. The objective is to connect the geometric statement “closest point in a subspace” to practical regression code and to know where ordinary least squares assumptions stop supporting statistical conclusions.",
        "prerequisites": ["vectors-matrices", "norms-distances"],
        "objectives": [
            "Derive projection and least-squares optimality from residual orthogonality and the geometry of column space.",
            "Choose QR, SVD, pseudoinverse or regularization instead of relying blindly on normal equations or explicit inverse.",
            "Validate fits using rank, conditioning, residual structure, leakage-safe evaluation and production monitoring.",
        ],
        "answer": "Least squares chooses x̂ minimizing `||Ax−b||²`. At the optimum the residual r=b−Ax̂ is orthogonal to the column space, giving `AᵀA x̂=Aᵀb`. The fitted values are the projection of b onto Col(A). Normal equations are useful for derivation but square the condition number; production solvers use QR or SVD. If A is rank-deficient, coefficients are not unique and the pseudoinverse returns a minimum-norm solution. Always include the intended intercept, inspect rank and conditioning, evaluate out of sample, and remember that unbiasedness or confidence intervals require assumptions beyond numerical minimization.",
        "keys": ["Fitted values lie in column space", "Residual is orthogonal to features", "Normal equations are a derivation", "QR/SVD are safer solvers", "Rank deficiency breaks coefficient uniqueness"],
        "why": "Linear regression, calibration, embeddings, filters and many optimization steps reduce to projection or least squares. The formula can produce numbers even when columns are duplicated, scales differ by orders of magnitude or data leaks future information. Understanding geometry reveals why coefficients become unstable, why residual checks matter and why computing an inverse is the wrong implementation. It also separates the deterministic approximation problem from statistical claims about noise and causality.",
        "intuition": "The columns of A span a flat surface of predictions that the model can express. Observation b usually lies off that surface. Least squares drops a perpendicular from b to the surface; the landing point is A x̂ and the leftover arrow is the residual. Coefficients describe how to combine columns to reach the landing point. If columns point in redundant directions, the landing point can be unique while the coordinate recipe is not.",
        "sections": [
            {"id": "projection-geometry", "title": "Projection onto vectors and subspaces", "body": "For nonzero vector a, the projection of b onto span(a) is `a(a^Tb)/(a^Ta)`. The coefficient is the aligned component measured relative to a's squared length. The residual `b−proj_a b` is orthogonal to a. If Q has orthonormal columns spanning a subspace, projection is `QQ^T b`, and P=QQ^T is symmetric and idempotent: `P^T=P`, `P²=P`. The complementary projector I−P maps onto the orthogonal complement.\n\nFor a general full-column-rank A, the projection matrix can be written `A(A^TA)^{-1}A^T`, but this expression is primarily conceptual. Forming it is unnecessary and often expensive; solving for coefficients or using an orthonormal factor is better. If columns are not independent, the inverse does not exist even though the subspace and its projection remain well defined. SVD/pseudoinverse supplies the orthogonal projector onto the column space.\n\nProjection depends on the inner product. Weighted least squares changes geometry so some residuals count more, commonly using inverse-variance weights under a noise model. Generalized least squares handles correlated errors through a covariance-aware metric. Weights must reflect the intended objective and be included consistently in evaluation; arbitrary large weights can create numerical and fairness problems."},
            {"id": "least-squares-derivation", "title": "Least squares and the normal equations", "body": "Define `f(x)=||Ax−b||²=(Ax−b)^T(Ax−b)`. Its gradient is `2A^T(Ax−b)`. Setting it to zero yields `A^TA x=A^Tb`, equivalent to residual orthogonality `A^T(b−Ax)=0`. When A has independent columns, `A^TA` is positive definite and the minimizer is unique. With dependent columns, there are multiple coefficient minimizers but all share the same fitted projection.\n\nAn intercept corresponds to a column of ones. Omitting it forces the fitted hyperplane through the origin and changes residual-mean and interpretation. Centering features and target can separate intercept computation, but preprocessing must be fitted on training data and replayed identically. Categorical one-hot encoding plus an intercept creates exact dependence if every category column is retained; drop a reference level or use a solver/regularization with an explicit identification convention.\n\nLeast squares minimizes vertical squared residuals in the modeled target coordinate. It is sensitive to outliers because squaring grows rapidly. It does not minimize perpendicular distance to both feature and target measurement errors, and it does not by itself produce causal effects. Statistical inference adds assumptions about error mean, variance, independence or distribution and data collection."},
            {"id": "solvers-rank", "title": "QR, SVD, pseudoinverse, and regularization", "body": "Solving normal equations by forming `A^TA` is numerically risky because its condition number is approximately the square of A's condition number. QR factorization writes A=QR with Q orthonormal and R triangular; solve `Rx=Q^Tb` without squaring conditioning. Householder QR is a standard stable dense method. SVD writes A=UΣV^T and exposes singular directions, rank, condition number and minimum-norm solutions. It costs more but is robust for rank deficiency and diagnostics.\n\nThe Moore-Penrose pseudoinverse `A^+=VΣ^+U^T` reciprocates nonzero singular values under a tolerance and returns the minimum-Euclidean-norm solution among least-squares minimizers. Tiny singular values amplify noise, so numerical rank depends on scale and tolerance. Do not interpret the library default as domain truth.\n\nRidge regression minimizes `||Ax−b||²+λ||x||²`, leading to `(A^TA+λI)x=A^Tb` (usually excluding the intercept from penalty). It shrinks unstable directions and guarantees a unique solution for λ>0 but introduces bias. Choose λ using validation without leakage. Feature scaling changes the effective ridge penalty, so preprocessing and penalty are one model. Lasso uses L1 penalty and changes the solver/geometry."},
            {"id": "diagnostics-production", "title": "Diagnostics, evaluation, and operation", "body": "Verify solver status, shape, rank, singular values/condition estimate, finite coefficients and residual orthogonality within tolerance. Compare predictions from two stable solvers on a small fixture. Inspect residuals versus fitted values, time, groups and important features for nonlinearity, heteroscedasticity, autocorrelation and bias. High leverage observations have unusual feature geometry and can influence the fit; large residual and leverage together deserve investigation, not automatic deletion.\n\nSplit evaluation according to deployment: chronological for future prediction, grouped for new entities, spatial for new regions. Fit scaling, imputation and encoding only on training folds. Compare to intercept/mean and simple domain baselines. Report prediction error and uncertainty separately from coefficient p-values. Robust regression, transformed targets, generalized linear models or nonlinear features may better match data and outcome.\n\nIn production, version column order, units, encoder, scaler, solver, regularization and training cutoff. Validate incoming schema/range/missingness, monitor prediction and residual drift when labels arrive, and alert on rank/conditioning changes. Bound matrix sizes and resource use, avoid logging sensitive raw rows, and audit protected-group performance. Keep training data lineage and a prior artifact for rollback. Refit only through the same tested pipeline; a mathematically equivalent feature reorder is not operationally equivalent without metadata."},
        ],
        "formal": "For A∈R^{m×n}, b∈R^m, minimize f(x)=||Ax−b||_2². Since ∇f=2A^T(Ax−b), optimality gives A^Tr=0 for r=b−Ax̂. If A has full column rank, x̂=(A^TA)^{-1}A^Tb conceptually. With SVD A=UΣV^T, x̂=A^+b=VΣ^+U^Tb is the minimum-norm least-squares solution. The fitted projector is P=AA^+.",
        "example": {"title": "Fit a line and verify orthogonality", "setup": "Fit y≈β0+β1x for x=(0,1,2) and y=(1,2,2).", "walkthrough": "The design matrix has rows `(1,x_i)`. Solving gives β0=7/6 and β1=1/2, so fitted values are `(7/6,5/3,13/6)`. Residuals `b−Aβ` are `(-1/6,1/3,-1/6)`. Their sum is zero, showing orthogonality to the intercept column; their dot product with x is also zero, showing orthogonality to the slope column. The data vector is decomposed into fitted projection plus residual. Use `lstsq`/QR rather than explicitly inverting A^TA. With only one x value or a duplicated feature column, coefficients would not be uniquely identified.", "conclusion": "Residual orthogonality is both the derivation and a powerful implementation check."},
        "mistakes": [
            {"mistake": "Use `(A.T@A)^{-1}@A.T@b` in production.", "correction": "Normal equations explain geometry but square conditioning; use `lstsq`, QR or SVD without an explicit inverse."},
            {"mistake": "A low training residual proves a useful model.", "correction": "Evaluate under deployment-like splits and inspect residual structure, leakage, baseline improvement and stability."},
            {"mistake": "Rank-deficient coefficients have a unique interpretation.", "correction": "Many coefficient vectors yield the same projection; pseudoinverse selects one convention and regularization changes the objective."},
        ],
        "followups": [
            {"question": "Why is the residual orthogonal to every feature column?", "answer": "Any component along the column space could be added to the fitted vector to reduce squared distance, so at the closest point none remains."},
            {"question": "Why prefer QR to normal equations?", "answer": "It solves through an orthonormal/triangular factorization without forming A^TA and avoids squaring the condition number."},
            {"question": "What does the pseudoinverse return?", "answer": "A least-squares solution, specifically the minimum-Euclidean-norm one when coefficients are not unique."},
        ],
        "production": "Use `lstsq`/QR/SVD with explicit rank and tolerance diagnostics; never form an inverse for solving. Version features, preprocessing, solver, penalty and cutoff. Use leakage-safe splits, baselines and residual/slice diagnostics, validate schema/finiteness/conditioning, monitor feature and residual drift, protect training data and keep a reproducible prior artifact for rollback.",
        "exercises": [
            {"difficulty": "recall", "prompt": "What equation expresses least-squares residual orthogonality?", "solution": "A^T(b−Ax̂)=0, equivalently the normal equations A^TAx̂=A^Tb."},
            {"difficulty": "application", "prompt": "When would SVD be preferable to a normal-equation solve?", "solution": "When rank deficiency, ill-conditioning, pseudoinverse/minimum norm or singular-value diagnostics matter."},
            {"difficulty": "diagnosis", "prompt": "Predictions are stable but individual coefficients change wildly across retraining. Why?", "solution": "Strong collinearity creates nearly null directions: many coefficient combinations produce similar fitted values. Inspect singular values and use redesign or regularization."},
        ],
        "resources": ["mit-linear-algebra", "numpy-linalg", "boyd-convex"],
        "notes": [
            {"resource": "mit-linear-algebra", "contribution": "Provides projection, orthogonality, least squares, QR/subspaces and pseudoinverse foundations."},
            {"resource": "numpy-linalg", "contribution": "Documents production `lstsq`, QR, SVD, rank, solve and pseudoinverse routines used instead of explicit normal-equation inversion."},
            {"resource": "boyd-convex", "contribution": "Connects least-squares objectives, regularization, optimality and numerical solution to convex optimization."},
        ],
        "visuals": [
            {"type": "flow", "title": "Least squares as orthogonal decomposition", "items": ["Observation b", "Column space Col(A)", "Closest expressible point A x̂", "Residual r=b−A x̂", "Check Aᵀr=0"], "caption": "The fitted vector lies in the model subspace and the leftover is perpendicular to every feature direction.", "afterSection": "projection-geometry"},
            {"type": "compare", "title": "Same objective, different numerical routes", "left": {"title": "Normal equations", "items": ["Useful derivation", "Forms AᵀA", "Squares conditioning", "Avoid explicit inverse"]}, "right": {"title": "QR / SVD", "items": ["QR: stable full-rank solve", "SVD: rank and null directions", "Pseudoinverse / minimum norm", "Explicit tolerance diagnostics"]}, "caption": "Mathematical equivalence in exact arithmetic does not imply equal numerical stability.", "afterSection": "solvers-rank"},
        ],
        "lab": {
            "goal": "Project by solving least squares and verify the normal-equation, orthogonality, minimum-error and NumPy invariants.",
            "language": "python",
            "buildIt": "def solve_two_by_two(a,b,c,d,u,v):\n    det=a*d-b*c\n    if abs(det)<1e-12: raise ValueError('singular')\n    return ((u*d-b*v)/det,(a*v-u*c)/det)\n\ndef least_squares_line(xs,ys):\n    n=len(xs); sx=sum(xs); sxx=sum(x*x for x in xs); sy=sum(ys); sxy=sum(x*y for x,y in zip(xs,ys))\n    return solve_two_by_two(n,sx,sx,sxx,sy,sxy)",
            "useIt": "import numpy as np\nxs=np.array([0.,1.,2.]); y=np.array([1.,2.,2.])\nbeta=np.array(least_squares_line(xs,y))\nA=np.column_stack([np.ones_like(xs),xs])\nlibrary,residuals,rank,singular=np.linalg.lstsq(A,y,rcond=None)\nfitted=A@beta; residual=y-fitted",
            "verifyIt": "assert np.allclose(beta,[7/6,1/2])\nassert np.allclose(beta,library)\nassert rank==2 and singular[-1]>0\nassert np.allclose(A.T@residual,[0.,0.],atol=1e-12)\nassert np.allclose(fitted+residual,y)\nfor delta in ([.01,0.],[0.,.01],[-.01,.02]):\n    assert np.linalg.norm(A@(beta+delta)-y)>=np.linalg.norm(residual)-1e-12",
            "shipIt": "Use target-library QR/SVD least squares with rank/condition telemetry, leakage-safe preprocessing and evaluation, versioned features/artifacts, drift monitoring and a prior reproducible model for rollback.",
        },
    })

    apply_chapter(lessons["eigen-svd"], {
        "description": "Eigenvectors identify directions preserved by a square linear transformation up to scale; singular value decomposition (SVD) gives an orthonormal input/output basis and nonnegative gains for any rectangular matrix. This chapter distinguishes eigendecomposition from SVD, derives their geometry, and connects them through `AᵀA` and `AAᵀ`. You will learn when a real matrix may lack a complete real eigenbasis, why symmetric matrices behave especially well, how singular values reveal rank and conditioning, and how truncated SVD yields the best low-rank approximation under standard norms. The chapter connects these ideas to principal component analysis, latent semantic structure, image compression, pseudoinverse and iterative power methods while separating centered covariance PCA from an uncentered matrix factorization. A worked 2×2 example verifies reconstruction and rank-one error. The lab implements power iteration and uses NumPy SVD with sign-invariant checks. Production guidance covers scaling, missing data, randomized algorithms, component stability, sign/rotation ambiguity, reconstruction versus downstream utility, privacy, resource cost and rollback. The aim is to make decompositions tools for understanding which directions a system amplifies, suppresses or cannot identify—not mysterious functions that merely return three arrays.",
        "prerequisites": ["vectors-matrices", "projections-least-squares"],
        "objectives": [
            "Explain eigenvectors/eigenvalues and singular vectors/values geometrically and state when each decomposition applies.",
            "Use singular values to reason about rank, conditioning, pseudoinverse, energy and optimal low-rank approximation.",
            "Apply PCA or truncated SVD without leakage, centering mistakes or invalid interpretations of unstable components.",
        ],
        "answer": "An eigenvector v of square A satisfies Av=λv, so its direction is preserved and scaled by eigenvalue λ. General matrices may have complex eigenvalues or lack a full eigenbasis; real symmetric matrices have orthonormal eigenvectors and real eigenvalues. Any m×n matrix has an SVD `A=UΣVᵀ`: V gives orthonormal input directions, Σ nonnegative gains, and U the corresponding output directions. Singular values expose rank and conditioning, and keeping the top k terms gives the best rank-k approximation in Frobenius and spectral norm. PCA is SVD/eigendecomposition applied to centered data/covariance, with preprocessing fitted on training data.",
        "keys": ["Eigenvectors preserve direction", "SVD works for rectangular matrices", "Singular values quantify gain", "Truncation is optimal for reconstruction norms", "PCA requires centering and leakage control"],
        "why": "Decompositions power dimensionality reduction, compression, latent factors, spectral clustering, covariance analysis, stable least squares and condition diagnostics. Misuse is common: calling singular vectors eigenvectors, performing PCA without centering, fitting components before splitting, treating sign flips as model drift, or assuming high explained variance guarantees predictive value. First-principles geometry explains the outputs and their limitations.",
        "intuition": "A general matrix maps the unit sphere in its input space to an ellipsoid in its output space. Right singular vectors are orthogonal input directions along the ellipsoid's axes; singular values are their stretch factors; left singular vectors point along the resulting output axes. Eigenvectors instead ask for directions that remain on their own line inside the same square input/output space.",
        "sections": [
            {"id": "eigen-geometry", "title": "Eigenvalues, eigenvectors, and symmetric structure", "body": "For square A, a nonzero vector v is an eigenvector if Av=λv. Scaling v gives the same direction, so normalization is conventional. Eigenvalues satisfy `det(A−λI)=0`. Repeated eigenvalues can have one or multiple independent eigenvectors. A matrix is diagonalizable when it has a basis of eigenvectors, giving `A=VΛV^{-1}` and making powers easy: `A^t=VΛ^tV^{-1}`. Not every matrix is diagonalizable, and real matrices can have complex eigenpairs.\n\nReal symmetric matrices are special: the spectral theorem gives real eigenvalues and an orthonormal eigenbasis, `A=QΛQ^T`. Positive semidefinite matrices have nonnegative eigenvalues and define nonnegative quadratic forms. Covariance and Gram matrices have this structure, enabling stable geometric interpretation. For a Markov transition convention, a dominant eigenvector can describe stationary behavior under appropriate conditions; network spectral methods depend on which Laplacian/adjacency normalization is used.\n\nEigenvalue magnitude often governs repeated linear dynamics, but non-normal matrices can show transient amplification not predicted by eigenvalues alone. Eigenvector conditioning matters. Production conclusions should not reduce a general dynamical system to “largest eigenvalue wins” without checking diagonalizability, normalization and the actual operator."},
            {"id": "svd-geometry", "title": "Singular value decomposition and fundamental subspaces", "body": "For A∈R^{m×n}, SVD is `A=UΣV^T`. In a reduced SVD of rank r, U has r orthonormal columns in R^m, V has r orthonormal columns in R^n, and diagonal Σ contains singular values `σ1≥…≥σr>0`. Applying A first expresses x in the right-singular basis V, scales components by σ, and expresses the result in U. Null-space right singular directions have zero gain.\n\nThe right singular vectors are eigenvectors of `A^TA` with eigenvalues σ²; left singular vectors are eigenvectors of `AA^T`. This connection avoids conflating dimensions: A's singular vectors live in different spaces when A is rectangular. Rank equals the number of nonzero singular values in exact arithmetic. The spectral norm is σ1, the Frobenius norm squared is the sum of σ_i², and full-rank condition number is σ1/σmin. Tiny values amplify noise in inverse problems.\n\nThe pseudoinverse `A^+=VΣ^+U^T` reverses nonzero directions and zeroes the null space. A tolerance determines which values count as numerical zero. Scaling features changes singular values, components and condition, so compare only under a fixed representation."},
            {"id": "low-rank-pca", "title": "Low-rank approximation and PCA", "body": "Writing SVD as `A=Σ_i σ_i u_i v_i^T` expresses A as rank-one components. The Eckart–Young–Mirsky theorem says truncating after k components gives a best rank-k approximation under spectral and Frobenius norms. The squared Frobenius reconstruction error is `Σ_{i>k}σ_i²`. This is an optimal statement for those matrix norms, not necessarily for classification accuracy, fairness, interpretability or perceptual quality.\n\nPrincipal component analysis centers data matrix X by the training mean. Right singular vectors of centered X are principal feature directions; scores are XV, and covariance eigenvalues are proportional to σ² depending on the covariance denominator. Explained variance ratio reports reconstruction variance, not supervised usefulness. Standardizing features changes PCA from covariance geometry toward correlation geometry and should follow unit/goal reasoning. Sparse/truncated SVD on term-document matrices is often applied without centering because centering destroys sparsity; call the method accurately.\n\nFit centering, scaling and components only on training data. Transform validation/test with those fitted parameters. Choose k using reconstruction, downstream validation, latency/storage and slice behavior. Component signs are arbitrary, and nearly equal singular values allow rotations within a subspace; compare subspaces or reconstructed outputs rather than raw columns alone."},
            {"id": "algorithms-operation", "title": "Algorithms and production operation", "body": "Dense full SVD is expensive for very large matrices. If only top components are needed, Lanczos/Krylov or randomized SVD methods use matrix-vector products and subspace iteration. Power iteration repeatedly normalizes Av to approach a dominant eigenvector when spectral separation and initialization conditions are favorable; convergence slows when leading magnitudes are close and can miss components orthogonal to initialization. Sparse and linear-operator interfaces avoid materializing huge matrices.\n\nValidate reconstruction `A≈UΣV^T`, orthonormality `U^TU≈I`, `V^TV≈I`, sorted nonnegative values and expected residual. Use relative tolerances tied to dtype and norm. Compare randomized results across seeds by subspace angles or reconstruction, not signs. Monitor iteration convergence and fallback on nonconvergence. Mixed precision can distort small singular values, while oversubscribed BLAS threads can hurt latency.\n\nVersion row/feature definition, centering, scaling, missing-value treatment, k, solver, seed and tolerance. Monitor input scale/covariance drift, explained/reconstruction error, downstream metrics, component/subspace stability, latency and memory. Decompositions may encode sensitive population structure; restrict artifacts and evaluate subgroup effects. Keep a prior transform plus compatible downstream model/index for rollback, since changing the basis invalidates stored coordinates."},
        ],
        "formal": "Eigenpair: Av=λv for square A and v≠0. SVD: A=UΣV^T with orthonormal U,V and σ_i≥0. Then A^TA v_i=σ_i²v_i and AA^T u_i=σ_i²u_i. Rank-r A has r positive singular values. The truncated A_k=Σ_{i=1}^kσ_i u_i v_i^T minimizes ||A−B||_2 and ||A−B||_F over rank(B)≤k, with ||A−A_k||_F²=Σ_{i>k}σ_i².",
        "example": {"title": "Diagonal stretch and rank-one approximation", "setup": "Let A=diag(3,1), a transformation that stretches the first coordinate three times and preserves the second.", "walkthrough": "Its eigenvectors and singular vectors are the coordinate axes. Eigenvalues are 3 and 1; singular values are also 3 and 1 because A is symmetric positive. Full SVD reconstructs A exactly. The best rank-one approximation keeps `3 e1 e1^T`, producing diag(3,0). Its spectral error is 1 and squared Frobenius error is 1, equal to the discarded singular value contributions. If the second axis contained crucial rare-class information, optimal reconstruction error would not guarantee optimal classification. A sign flip of e1 in both left/right vectors represents the same component.", "conclusion": "Singular values quantify directional gain and reconstruction loss, but the downstream task decides whether a discarded direction matters."},
        "mistakes": [
            {"mistake": "Every square matrix has an orthonormal eigenbasis.", "correction": "Real symmetric matrices do; general matrices may be non-normal, defective or have complex eigenpairs."},
            {"mistake": "PCA on all data before splitting is harmless preprocessing.", "correction": "The mean and components learn validation/test distribution, causing leakage; fit only on training data."},
            {"mistake": "Component sign changes indicate a different solution.", "correction": "Singular/eigenvectors are sign-ambiguous, and repeated/near-equal values permit basis rotations; compare subspaces/reconstruction."},
        ],
        "followups": [
            {"question": "How are eigenvalues and singular values related?", "answer": "Singular values of A are square roots of eigenvalues of positive-semidefinite A^TA; they are nonnegative and apply to rectangular A."},
            {"question": "What does a tiny singular value imply?", "answer": "The map nearly erases that input direction, so inversion/coefficients can amplify noise and the problem is ill-conditioned."},
            {"question": "What does truncated SVD optimize?", "answer": "Matrix reconstruction error among rank-k approximations under spectral and Frobenius norms, not every downstream objective."},
        ],
        "production": "Fit centering/scaling and decomposition on training data only; version representation, k, solver, seed and tolerances. Validate orthogonality, reconstruction, convergence, rank/condition and downstream metrics across slices. Use sparse/randomized operators for scale with exact-subset regression, control dtype/threads and monitor covariance/subspace drift. Protect sensitive components and roll back the transform with all dependent coordinates/models.",
        "exercises": [
            {"difficulty": "recall", "prompt": "Where do left and right singular vectors live for an m×n matrix?", "solution": "Left singular vectors live in the m-dimensional output space; right singular vectors live in the n-dimensional input space."},
            {"difficulty": "application", "prompt": "Why use truncated SVD for a sparse term-document matrix rather than centered PCA?", "solution": "Centering can destroy sparsity; uncentered truncated SVD preserves sparse computation, though its components are not covariance PCA."},
            {"difficulty": "diagnosis", "prompt": "Two runs have flipped component signs but identical reconstruction. Is that a failure?", "solution": "No. Signs are arbitrary when paired consistently. Compare reconstruction or subspace, not raw sign."},
        ],
        "resources": ["mit-linear-algebra", "3b1b-linear-algebra", "numpy-linalg"],
        "notes": [
            {"resource": "mit-linear-algebra", "contribution": "Provides eigenvalue, symmetric matrix, positive-definite, SVD, pseudoinverse and image-compression foundations."},
            {"resource": "3b1b-linear-algebra", "contribution": "Offers geometric explanations of eigenvectors, basis change and transformations that complement the formal derivation."},
            {"resource": "numpy-linalg", "contribution": "Documents current eigen/SVD, rank, condition and pseudoinverse routines and their array behavior."},
        ],
        "visuals": [
            {"type": "flow", "title": "SVD maps a sphere to an ellipsoid", "items": ["Rotate into right-singular basis Vᵀ", "Scale axes by singular values Σ", "Rotate into output basis U", "Zero-gain axes form null space"], "caption": "Right directions, nonnegative gains and left directions can describe any rectangular linear map.", "afterSection": "svd-geometry"},
            {"type": "compare", "title": "Eigen versus singular decomposition", "left": {"title": "Eigen", "items": ["Square operator", "Same input/output direction", "May be complex or defective", "Symmetric case is orthonormal"]}, "right": {"title": "SVD", "items": ["Any rectangular matrix", "Separate input/output bases", "Always nonnegative gains", "Direct rank/condition diagnostics"]}, "caption": "The decompositions answer related but distinct geometric questions.", "afterSection": "eigen-geometry"},
        ],
        "lab": {
            "goal": "Implement dominant-eigenvector power iteration, then verify SVD reconstruction, orthogonality, sign-invariant eigen behavior and optimal rank-one error.",
            "language": "python",
            "buildIt": "import math\n\ndef power_iteration(a,start,steps=100):\n    v=list(map(float,start))\n    for _ in range(steps):\n        w=[sum(row[j]*v[j] for j in range(len(v))) for row in a]\n        norm=math.sqrt(sum(x*x for x in w))\n        if norm==0: raise ValueError('zero iterate')\n        v=[x/norm for x in w]\n    av=[sum(row[j]*v[j] for j in range(len(v))) for row in a]\n    value=sum(v[i]*av[i] for i in range(len(v)))\n    return value,v",
            "useIt": "import numpy as np\nA=np.array([[3.,0.],[0.,1.]])\nvalue,vector=power_iteration(A.tolist(),[1.,1.])\nU,s,Vt=np.linalg.svd(A,full_matrices=False)\nrank1=s[0]*np.outer(U[:,0],Vt[0])\nreconstruction=(U*s)@Vt",
            "verifyIt": "assert abs(value-3.0)<1e-10\nassert abs(abs(vector[0])-1.0)<1e-8\nassert np.allclose(reconstruction,A)\nassert np.allclose(U.T@U,np.eye(2)) and np.allclose(Vt@Vt.T,np.eye(2))\nassert np.allclose(s,[3.,1.])\nassert np.isclose(np.linalg.norm(A-rank1,2),s[1])\nassert np.isclose(np.linalg.norm(A-rank1,'fro')**2,sum(s[1:]**2))",
            "shipIt": "Use stable library/randomized decompositions, training-only preprocessing, convergence and reconstruction checks, versioned basis metadata, downstream slice evaluation, drift monitoring and compatible rollback artifacts.",
        },
    })

    SOURCE.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    apply()
